storage: /verdaccio/storage
web:
  enable: true
  title: Verdaccio
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npm.taobao.org
packages:
  '@ngiq/*':
    access: $all
    publish: $authenticated
    proxy: ngiq
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}
